type User {
  netlifyID: ID!
  stripeID: ID!
}

type Account {
  netlifyID: ID!
  stripeID: ID!
}

type Query {
  getUserByNetlifyID(netlifyID: ID!): User!
  getUserByStripeID(stripeID: ID!): User!
  getAccountByNetlifyID(netlifyID: ID!): Account!
  getAccountByStripeID(stripeID: ID!): Account!
}