backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:  
  - name: "author"
    identifier_field: username
    label: "Author"
    format: 'json'
    folder: "client/assets/content/author"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Username", name: "username", widget: "string" }
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Profile Picture", name: "profilePicture", widget: "image" }
      - { label: 'Category', name: 'category', widget: 'list', default: ["システムエンジニア", "DBA", "プログラマー", "デザイナー"] }
      - { label: 'Body', name: 'body', widget: 'markdown' }


  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'client/assets/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Author", name: "author", widget: "relation", collection: "author", searchFields: ["title"], valueField: "{{slug}}", displayFields: ["{{title}} - {{username}}"] }

  - name: 'plan'
    label: 'Plan'
    format: 'json'
    folder: 'client/assets/content/plan'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Status', name: 'status', widget: 'select', options: ["Active", "Hidden"] }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Author", name: "author", widget: "relation", collection: "author", searchFields: ["title"], valueField: "{{slug}}", displayFields: ["{{title}} - {{username}}"]}