backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: client/static/img
public_folder: /img

collections:  
  - name: 'blog'
    label: 'Blog'
    description: >
      技術情報を共有するためのブログ。メンターとしてのアピールや説明に利用してください。
    format: 'json'
    folder: 'client/assets/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Author", name: "author", widget: "relation", collection: "author", searchFields: ["title"], valueField: "{{slug}}", displayFields: ["{{title}} - {{username}}"] }

  - name: 'plan'
    label: 'Plan'
    description: >
      ユーザーに販売するプランの詳細を登録します。
    format: 'json'
    folder: 'client/assets/content/plan'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Status', name: 'status', widget: 'select', options: ["Active", "Hidden"] }
      - { label: 'Stripe SKU', name: 'sku', widget: 'string' }
      - {
          label: "Price",
          name: "price",
          widget: "number",
          default: 100,
          valueType: "int",
          min: 100,
          max: 500000,
          step: 100
      }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Author", name: "author", widget: "relation", collection: "author", searchFields: ["title"], valueField: "{{slug}}", displayFields: ["{{title}} - {{username}}"]}
      - {
        label: "Hashtag",
        name: "hashtags",
        widget: "relation",
        collection: "settings",
        file: "hashtag", 
        searchFields: ["hashtags.*.value"],
        valueField: "hashtags.*.value",
        displayFields: ["hashtags.*.label"],
        multiple: true
      }

  - name: "author"
    identifier_field: username
    label: "Author"
    description: >
      サポートするメンターのユーザー情報を登録します。自分の情報のみ更新するようにしてください。
    format: 'json'
    folder: "client/assets/content/author"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Username", name: "username", widget: "string" }
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Profile Picture", name: "profilePicture", widget: "image" }
      - {
        label: "Category",
        name: "categories",
        widget: "relation",
        collection: "settings",
        file: "category", 
        searchFields: ["categories.*.value"],
        valueField: "categories.*.value",
        displayFields: ["categories.*.label"],
        multiple: true
      }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'settings'
    label: 'Settings'
    format: 'json'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'category'
        label: 'Category'
        format: 'json'
        file: 'client/assets/content/category.json'
        delete: false # Prevent users from deleting documents in this collection
        editor:
          preview: false
        fields:
          - name: categories
            label: Categories
            label_singular: 'Category'
            widget: list
            fields:
              - { label: 'Label', name: 'label', widget: 'string', hint: '表示する名称を記入' }
              - { label: 'Value', name: 'value', widget: 'string', hint: 'キャメル型の英数字で値を記入' }
              
      - name: 'hashtag'
        label: 'Hashtag'
        format: 'json'
        file: 'client/assets/content/hashtag.json'
        fields:
          - name: hashtags
            label: Hashtags
            label_singular: 'Hashtag'
            widget: list
            fields:
              - { label: 'Label', name: 'label', widget: 'string', hint: '表示する名称を記入' }
              - { label: 'Value', name: 'value', widget: 'string', hint: 'キャメル型の英数字で値を記入' }
              
      - name: 'product'
        label: 'Product'
        format: 'json'
        file: 'client/assets/content/product.json'
        fields:
          - name: products
            label: Products
            label_singular: 'Product'
            widget: list
            fields:
              - { label: 'Label', name: 'label', widget: 'string', hint: '表示する商品名を記入' }
              - {
                  label: "Price",
                  name: "price",
                  widget: "number",
                  default: 100,
                  valueType: "int",
                  min: 100,
                  max: 500000,
                  step: 100,
                  hint: 'Stripeで作成した金額'
                }
              - { label: 'Value', name: 'value', widget: 'string', hint: 'StripeのSKUのIDを記入' }